services:
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    image: react-app
    user: myuser
    volumes:
      - ./react-app:/app
      - vite_node_modules:/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - postgres
    environment:
      - VITE_API_URL=http://localhost:8080/api
    networks:
      - app-network

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_password
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: always
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: 'no'
    expose:
      - 6379

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
      - redis
      - react-app
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  postgres_data:
  vite_node_modules:

secrets:
  db_password:
    file: ./app-secrets/db_password.txt
  secret_key:
    file: ./app-secrets/secret_key.txt

networks:
  app-network:
    driver: bridge