version: '3.7'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_password
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: always
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  haproxy:
    image: haproxy:latest
    ports:
      - "7800:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - project_network

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./app-secrets/db_password.txt
  secret_key:
    file: ./app-secrets/secret_key.txt

networks:
  project_network: