services:
  react-app:
    build: ./react-app
    image: react-app
    user: appuser
    volumes:
      - ./react-app/src:/app/src  # Mount the src folder from react-app to /app/src in the container
      - ./react-app/public:/app/public  # Mount the public folder from react-app to /app/public in the container
      - /app/node_modules  # Persist node_modules in the container
    ports:
      - 5173:5173
    depends_on:
      - postgres
    environment:
      - VITE_API_URL=https://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true  # Ensure file changes trigger live reloading in Docker
    command: ["yarn", "dev"]  # Run the React app in development mode
    working_dir: /app
    stdin_open: true # Keeps stdin open to support live reloading
    tty: true # Allocate a pseudo-TTY to keep the container interactive
    networks:
      - app-network

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_password
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: always
    ports:
      - 5432:5432
  
  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DATABASE_URL_FILE: /run/secrets/database_url
      POOL_MODE: transaction
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    depends_on:
      - postgres

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: 'no'
    expose:
      - 6379

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/cert.pem:/etc/nginx/cert.pem:ro
      - ./ssl/key.pem:/etc/nginx/key.pem:ro
    depends_on:
      - postgres
      - redis
      - react-app
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./app-secrets/db_password.txt
  secret_key:
    file: ./app-secrets/secret_key.txt
  database_url:
    file: ./app-secrets/database_url.txt

networks:
  app-network:
    driver: bridge