version: "3.8"

services:
  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    image: backend-api
    volumes:
      - ./backend-api/:/usr/src/app/  # Mount code for live updates during development
    secrets:
      - db_password
      - secret_key
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key
      REDIS_URL: redis://redis:6379/0
    expose:
      - 8000:8000
    depends_on:
      - database
      - redis
    deploy:
      replicas: 3
    restart: 'no'
    networks:
      - backend_network 

  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - db_password
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: 'no'
    ports:
      - 5432:5432
    networks:
      - backend_network

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: 'no'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7800:7800
    depends_on:
      - backend-api
    restart: 'no'
    networks:
      - backend_network

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./app-secrets/db_password.txt
  secret_key:
    file: ./app-secrets/secret_key.txt

networks:
  backend_network: